### PR TITLE
WIP Start planning how to bring Bitbucket/Bamboo into this

### PR DESCRIPTION
**Pull request by de1ux**
@bign8 I'm going to start working on swappable clients to support the Bitbucket/Bamboo stack I have at SoFi. 

If you have any strong opinions about this, or want to help with the Github client, let me know.

### CODE REVIEW

**Comment by bign8** [comment]
Great idea!
I'll help with the github client once the models are a little more solidified.
I have started using [GitLab](https://about.gitlab.com/) for a few projects, so that would be fun to support too.

**Comment by de1ux** [comment]
I've been sidetracked evaluating https://github.com/maxogden/menubar, which would let us write a richer UI and get around the janky Bitbar-specific bash output.

**Comment by de1ux** [comment]
Will update this week/end

**Comment by de1ux** [comment]
The more and more I play with this, the less I like the way Electron looks. 
screen shot 2018-01-23 at 7 00 00 am

**Comment by de1ux** [comment]
@bign8 the scaffolding is all here to do this in Electron, but I'm getting cold feet because of all the Electron CSS styling needed to make this look macOS native. And even then, it'll look odd. [Here's an example at how odd Electron looks trying to style as a native window](https://github.com/kevinsawicki/tray-example).

**Comment by de1ux** [comment]
Anyways, I'm going to scrap all of this and reuse the existing golang/bitbar codebase. Bitbar's lack of features and its hanky-janky bash input are really gross, but I don't think we want to dump it for Electron's poor aesthetics.

**Pull request closed without merging**
